// Core data model for the app.
// These types mirror the Supabase table schemas defined in /supabase/schema.sql.

export interface Tool {
  id: string;
  name: string;
  category: string;
  description: string;
  link: string;
  created_at: string;
}

export interface Category {
  id: string;
  name: string;
}

// Shape of the form used on the Submit Tool page.
// Excludes id and created_at, which are generated by the database.
export type NewTool = Omit<Tool, "id" | "created_at">;
